version: '3'
services:
  vpn-server:
    image: "kylemanna/openvpn"
    container_name: "vpn"
    restart: "unless-stopped"
    user: "0:${PGID}"
    networks:
      - "vpn"
    ports:
      - "1194:1194/udp"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "$STACK_DATA/openvpn:/etc/openvpn"
networks:
  vpn: